// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repo

import (
	"database/sql"
)

type Setting struct {
	UserPk     string
	PetSpecies string
	PetColor   sql.NullString
	InsertedAt sql.NullInt64
	PetName    string
}

type User struct {
	PublicKey            string
	Name                 string
	NextActivityChangeAt int64
}
